In [1]:
import numpy as np
from sklearn.datasets import load_linnerud
from sklearn.multioutput import MultiOutputRegressor
from sklearn.linear_model import Ridge

In [2]:
X, y = load_linnerud(return_X_y=True)
clf = MultiOutputRegressor(Ridge(random_state=123)).fit(X, y)
clf.predict(X[[0]])

array([[176.16484296,  35.0548407 ,  57.09000136]])

In [5]:
type(X), X.shape, y.shape

(numpy.ndarray, (20, 3), (20, 3))

In [6]:
X[0:5,:]

array([[  5., 162.,  60.],
       [  2., 110.,  60.],
       [ 12., 101., 101.],
       [ 12., 105.,  37.],
       [ 13., 155.,  58.]])

In [7]:
y[0:5,:]

array([[191.,  36.,  50.],
       [189.,  37.,  52.],
       [193.,  38.,  58.],
       [162.,  35.,  62.],
       [189.,  35.,  46.]])

In [9]:
clf.get_params()

{'estimator__alpha': 1.0,
 'estimator__copy_X': True,
 'estimator__fit_intercept': True,
 'estimator__max_iter': None,
 'estimator__normalize': False,
 'estimator__random_state': 123,
 'estimator__solver': 'auto',
 'estimator__tol': 0.001,
 'estimator': Ridge(random_state=123),
 'n_jobs': None}